wfe:
  api:
    key: '{cipher}AQECAHhvkz0gC16kOZuuGBYZ6Htij6TlUS+jhESy1JefKLzdWgAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDD6bd14QQdsYgrSRAQIBEIA7AopCiiJHlWpM7BUgJ5Nn7fKbBlAra9n82RyuA2XBBqPER/fDH8P6EOfYeqlBMX1Pf9aPve72V/e+bEQ='
    uri: http://api-uat.morningstar.com/wfe/v5/api/Wferest/
  pivotvalue: Total Wealth Including Unowned Balance
  accounts:
    - name: Super Account
    - name: Investment Account
  output:
    values:
      - ${wfe.pivotvalue}
  projection:
    name: Dynamic Request
    include_spend_down_need_estimate: false
    use_annuitized_wealth_advice: false
  taxable_account: Investment Account
  use_salary_curve: false
  treat_taxes_as_expenses: false
portfolios:
  models:
    p1:
      code: M0001
      name: Cautious
    p2:
      code: M0002
      name: Balanced
    p3:
      code: M0003
      name: Growth
source: application-dev.yaml
branch: master