portfolios:
  models:
    p1:
      code: M0001
      name: Cautious
    p2:
      code: M0002
      name: Balanced
    p3:
      code: M0003
      name: Growth
source: application-jenkins.yaml
branch: master
fsg:
  version: '201706'