wfe:
  api:
    key: '{cipher}AQECAHhvkz0gC16kOZuuGBYZ6Htij6TlUS+jhESy1JefKLzdWgAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDD6bd14QQdsYgrSRAQIBEIA7AopCiiJHlWpM7BUgJ5Nn7fKbBlAra9n82RyuA2XBBqPER/fDH8P6EOfYeqlBMX1Pf9aPve72V/e+bEQ='
    uri: http://api-uat.morningstar.com/wfe/v5/api/Wferest/
  percentiles:
    - name: optimistic
      percentile: 30
    - name: pessimistic
      percentile: 5
  pivotvalue: Total Wealth Including Unowned Balance
  accounts:
    - name: Super Account
    - name: Investment Account
  output:
    values:
      - ${wfe.pivotvalue}
  projection:
    name: Dynamic Request
    include_spend_down_need_estimate: false
    use_annuitized_wealth_advice: false
  taxable_account: Investment Account
  use_salary_curve: false
  treat_taxes_as_expenses: false
praemium:
  endpoint:
    url: 'https://apitest.praemium.biz/public/api'
  privilege:
    token-header: 'x-pps-token'
    token-value: '{cipher}AQECAHhvkz0gC16kOZuuGBYZ6Htij6TlUS+jhESy1JefKLzdWgAAAJ8wgZwGCSqGSIb3DQEHBqCBjjCBiwIBADCBhQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyO7ceCTCrSi8JocRYCARCAWLjEzXIipgGSm4nrovVB4isP5h88EH0PZDo5P0GYqnx7+3v3vgYnsqKiPzVNTwXRiXvESEmEo2vx6GyjwWOwabqYtOJ5YOmFrQkZaFszQi8f4wS/ptX2+jE='
    version-header: 'x-pps-api-version'
    version-value: '2017.03.01'
  portfolio_model:
    p1: Moderate
    p2: Balanced
    p3: Growth
fsg:
  version: '201706'
source: application-qa.yaml
branch: master
